cfg: .\models\yolov5s.yaml
data: .\data\guns.yaml
hyp: ''
epochs: 3
batch_size: 16
img_size:
- 1330
- 1330
rect: false
resume: false
nosave: true
notest: false
noautoanchor: false
evolve: false
bucket: ''
cache_images: true
weights: ''
name: ''
device: ''
multi_scale: false
single_cls: false
adam: false
sync_bn: false
local_rank: -1
total_batch_size: 16
world_size: 1
